export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
      <p className="text-gray-600 mb-4">Last updated: January 2, 2026</p>
      
      <h2 className="text-xl font-semibold mt-6 mb-3">1. Service Description</h2>
      <p className="text-gray-700 mb-4">
        QuiltPlannerPro provides AI-generated quilt patterns based on uploaded fabric images.
      </p>
      
      <h2 className="text-xl font-semibold mt-6 mb-3">2. Subscriptions</h2>
      <p className="text-gray-700 mb-4">
        Paid subscriptions are billed monthly or yearly. You can cancel anytime. 
        Refunds are handled on a case-by-case basis.
      </p>
      
      <h2 className="text-xl font-semibold mt-6 mb-3">3. User Content</h2>
      <p className="text-gray-700 mb-4">
        You retain ownership of images you upload. Images are processed temporarily 
        and not stored permanently. Generated patterns are yours to use for personal 
        or commercial quilting projects.
      </p>
      
      <h2 className="text-xl font-semibold mt-6 mb-3">4. Limitations</h2>
      <p className="text-gray-700 mb-4">
        Patterns are generated by AI and may require adjustment. We do not guarantee 
        patterns will work for all skill levels or fabric types.
      </p>
      
      <h2 className="text-xl font-semibold mt-6 mb-3">5. Contact</h2>
      <p className="text-gray-700">
        Questions? Email us at support@quiltplannerpro.com
      </p>
    </div>
  );
}