import Navigation from '@/components/Navigation';

export default function TermsPage() {
  return (
    <div className="min-h-screen" style={{background: 'linear-gradient(135deg, #FEF2F2 0%, #F0FDFA 50%, #FFFBEB 100%)'}}>
      <Navigation />
      
      <div className="py-12 px-4" style={{backgroundImage: 'url(/QuiltPlannerProBackGround.png)', backgroundSize: 'cover', backgroundPosition: 'center'}}>
        <div className="max-w-7xl mx-auto">
          <h1 className="text-4xl font-bold text-white mb-2">Terms of Service</h1>
          <p className="text-white text-opacity-90">Last updated: January 2, 2026</p>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-4 py-12">
      <h2 className="text-xl font-semibold mt-6 mb-3">1. Service Description</h2>
      <p className="text-gray-700 mb-4">
        QuiltPlannerPro provides AI-generated quilt patterns based on uploaded fabric images.
      </p>
      
      <h2 className="text-xl font-semibold mt-6 mb-3">2. Subscriptions</h2>
      <p className="text-gray-700 mb-4">
        Paid subscriptions are billed monthly or yearly. You can cancel anytime. 
        Refunds are handled on a case-by-case basis.
      </p>
      
      <h2 className="text-xl font-semibold mt-6 mb-3">3. User Content</h2>
      <p className="text-gray-700 mb-4">
        You retain ownership of images you upload. Images are processed temporarily 
        and not stored permanently. Generated patterns are yours to use for personal 
        or commercial quilting projects.
      </p>
      
      <h2 className="text-xl font-semibold mt-6 mb-3">4. Limitations</h2>
      <p className="text-gray-700 mb-4">
        Patterns are generated by AI and may require adjustment. We do not guarantee 
        patterns will work for all skill levels or fabric types.
      </p>
      
      <h2 className="text-xl font-semibold mt-6 mb-3">5. Contact</h2>
      <p className="text-gray-700">
        Questions? Email us at support@quiltplannerpro.com
      </p>
      </div>
    </div>
  );
}