import PDFDocument from 'pdfkit';

/**
 * Service for rendering PDF footers
 * Single Responsibility: Footer pagination rendering
 */
export class PDFFooterRenderer {
  /**
   * Render footer on all pages with pagination
   */
  renderFooter(doc: InstanceType<typeof PDFDocument>): void {
    // Flush pages before counting
    if (typeof (doc as any).flushPages === 'function') {
      (doc as any).flushPages();
    }

    const pageCount = (doc as any).bufferedPageRange().count;
    
    if (pageCount > 0) {
      for (let i = 0; i < pageCount; i++) {
        try {
          (doc as any).switchToPage(i);
          doc
            .fontSize(8)
            .fillColor('#9CA3AF')
            .text(
              `Generated by QuiltPlannerPro on ${new Date().toLocaleDateString()} | Page ${i + 1} of ${pageCount}`,
              50,
              750,
              { align: 'center', width: 495 }
            );
        } catch (footerErr) {
          console.error(`Footer: switchToPage(${i}) failed:`, footerErr);
        }
      }
    }
  }
}
